[package]
name = "jvm-classfile"
version = "0.1.0"
authors = ["KokaKiwi <kokakiwi@kokakiwi.net>"]
description = "Java class files reader"

[dependencies]
bitflags = "0.5"
byteorder = "0.5"
log = "*"
quick-error = "*"
