[workspace]
members = ["classfile"]

[package]
name = "jvm"
version = "0.1.0"
authors = ["KokaKiwi <kokakiwi@kokakiwi.net>"]

[dependencies]
clap = { version = "*", features = ["unstable"] }
env_logger = "*"
error-chain = "*"
jvm-classfile = { path = "classfile" }
log = "*"
